const { query } = require('../db');

async function getReport(req, res) {
  try {
    const { projectId } = req.params;
    
    // Get project
    const projectResult = await query(
      'SELECT id, state, stage, created_at, updated_at FROM projects WHERE id = $1',
      [projectId]
    );
    
    if (projectResult.rows.length === 0) {
      return res.status(404).json({ error: 'Project not found' });
    }
    
    const project = projectResult.rows[0];
    
    // Get idea (latest)
    const ideaResult = await query(
      'SELECT content FROM ideas WHERE project_id = $1 ORDER BY created_at DESC LIMIT 1',
      [projectId]
    );
    const idea = ideaResult.rows.length > 0 ? ideaResult.rows[0].content : 'No idea found';
    
    // Get feasibility decision
    const feasibilityDecisionResult = await query(
      'SELECT outcome FROM decisions WHERE project_id = $1 AND stage = $2 ORDER BY created_at DESC LIMIT 1',
      [projectId, 'feasibility']
    );
    const outcome = feasibilityDecisionResult.rows.length > 0 
      ? feasibilityDecisionResult.rows[0].outcome 
      : 'Pending';
    
    // Get feasibility_report artifact
    const feasibilityArtifactResult = await query(
      'SELECT content FROM artifacts WHERE project_id = $1 AND stage = $2 AND type = $3 ORDER BY created_at DESC LIMIT 1',
      [projectId, 'feasibility', 'feasibility_report']
    );
    
    let summary = 'Feasibility analysis completed'; // Fallback
    let risks = 'Standard project risks'; // Fallback
    
    if (feasibilityArtifactResult.rows.length > 0) {
      try {
        const feasibilityContent = JSON.parse(feasibilityArtifactResult.rows[0].content);
        if (feasibilityContent.summary) {
          summary = feasibilityContent.summary;
        }
        if (feasibilityContent.risks) {
          risks = feasibilityContent.risks;
        }
      } catch (e) {
        // Use fallbacks if JSON parse fails
      }
    }
    
    // Get planning_plan artifact
    const planningArtifactResult = await query(
      'SELECT content FROM artifacts WHERE project_id = $1 AND stage = $2 AND type = $3 ORDER BY created_at DESC LIMIT 1',
      [projectId, 'planning', 'planning_plan']
    );
    
    let timeline = 'TBD'; // Fallback
    let phases = 'Multiple phases'; // Fallback
    let components = 'Core components defined'; // Fallback
    
    if (planningArtifactResult.rows.length > 0) {
      try {
        const planningContent = JSON.parse(planningArtifactResult.rows[0].content);
        if (planningContent.timeline) {
          timeline = planningContent.timeline;
        }
        if (planningContent.phases) {
          if (Array.isArray(planningContent.phases)) {
            phases = planningContent.phases.join(', ');
          } else {
            phases = planningContent.phases;
          }
        }
        if (planningContent.components) {
          if (Array.isArray(planningContent.components)) {
            components = planningContent.components.join(', ');
          } else {
            components = planningContent.components;
          }
        }
      } catch (e) {
        // Use fallbacks if JSON parse fails
      }
    }
    
    // Generate report in exact schema order
    const generatedAt = new Date().toISOString();
    const status = project.stage || project.state || 'Unknown';
    
    const report = `# Project Report

## Header
- **Project ID:** ${project.id}
- **Generated:** ${generatedAt}
- **Status:** ${status}

## Executive Summary

### Your Idea
${idea}

## Feasibility Analysis

### Outcome
${outcome}

### Summary
${summary}

### Risks
${risks}

## Execution Plan

### Timeline
${timeline}

### Phases
${phases}

### Components
${components}

## Next Steps

Review the feasibility analysis and execution plan. Proceed with implementation when ready.

## Footer

Report generated by Conductor MVP.
`;
    
    res.setHeader('Content-Type', 'text/markdown');
    res.send(report);
  } catch (error) {
    console.error('Error generating report:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
}

module.exports = { getReport };

